baseURL = "https://hacman.netlify.com/"
languageCode = "en-us"
title = "Hackspace Manchester"
theme = "hacman-paper"

[menu]

  [[menu.nav]]
    identifier = "About"
    name = "About"
    external = false
    url = "/about/"
    weight = 1

  [[menu.nav]]
    name = "Areas"
    external = false
    url = "/areas/"
    weight = 10
  
  [[menu.nav]]
    name = "Membership"
    external = true
    url = "http://members.hacman.org.uk"
    weight = 20
