baseURL = "https://hacman.netlify.com/"
languageCode = "en-us"
title = "Hackspace Manchester"
theme = "hacman-paper"

[menu]

  [[menu.nav]]
    identifier = "About"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.nav]]
    name = "Areas"
    url = "/areas/"
    weight = 10

  [[menu.nav]]
    name = "Membership"
    url = "/membership/"
    weight = 20
